### ISSUE TITLE
"Run an internet speed test" tests with very distant servers

### ISSUE THREAD

**Issue by NekoAlosama** [mastercoms/tf2cfg#73] opened 2019-02-19 01:27 UTC
Using mastercomfig app 7.0.0-a.15 and running the speed test yields inaccurate results. 
For those that don't want to read the picture:

Regular speeds using speedtest.net (Miami, Florida server, ~249km away):  ~23 mbps down, ~1.9 mbps up
Speeds according to mastercomfig app (Tromsø, Norway server, NaN km away (lol)): <1 mbps down, <0.5 mbps up

I don't know if this is just an individual issue or just mastercomfig's.
![screenshot 6 _li](https://user-images.githubusercontent.com/47763383/52983849-f2af0200-33ba-11e9-920c-6b1c54f28d9d.jpg)

**Comment by seagullmania** [comment] 2019-02-19 05:47
Can confirmed this happens to me as well.

**Comment by NekoAlosama** [comment] 2019-02-19 21:44
Wouldn't it be a better idea just to be able to manually input our internet speeds?

**Comment by NekoAlosama** [comment] 2019-02-23 00:10
And on that note, can someone tell me what are the exact equations for rate, net_maxcleartime, and net_splitpacket_maxrate?

**Comment by PoorPocketsMcNewHold** [comment] 2019-02-24 17:58
I can confirm the same issue on my end, despite being in a totally other location in Europe. Strangely, With the exact same server.

**Comment by Spyro201** [comment] 2019-02-24 23:55
I'd also like to confirm this problem, it keeps connecting me to Norway as well despite not living anywhere near there. Due to this problem it causes the user to get a much lower upload and download speed. Well, unless you live in Norway I suppose.

**Comment by NekoAlosama** [comment] 2019-02-25 00:03
Welp I found a way to edit the settings to change the reported speeds.

In the "C:\Users\<your username>\AppData\Roaming\mastercomfig-app", there is a file titled "Settings".
Just open it with the text editor of your choice and edit the "upload-speed":xxx,"download-speed":yyy

So for me, I changed 
"upload-speed":1.249,"download-speed":1.993
to
"upload-speed":2.317,"download-speed":29.958
(i used speedtest.net, but used kbps then converted it to mbps
kbps -> mbps is more precise than just using mbps)

Also I saw on the Discord that mastercomfig specifically is dead and mastercoms is working on another service that allows less reliance on tf2 and enables community help

**Comment by mastercoms** [comment] 2019-05-14 14:01
Yep, unfortunately we can't access the API that speedtest uses to determine the best server, so have to sample a few servers manually from a list of speedtest servers. Entering the speed manually could work, but I would rather find a better automatic service.

**Comment by Xeogin** [comment] 2019-07-04 07:55
The DSLReports Speed Test is the best I've ever used and has an API:  https://www.dslreports.com/speedtest/api-available

**Comment by mastercoms** [comment] 2019-07-29 04:22
Closing because the mastercomfig 7 app is discontinued.

**Closed as completed by mastercoms** 2019-07-29 04:22 UTC
