### ISSUE TITLE
A bunch of HUD/Visual bugs.

### ISSUE THREAD

**Issue by jonnemenes** [mastercoms/tf2cfg#58] opened 2018-06-29 16:28 UTC
I don't know if I have to make an issue for each of the problems, so here it goes:
1)Weapon viewmodels do not show (even with r_drawviewmodel 1 in my custom.cfg file), unless I open the "Advanced Options" Menu while in a match, then in that case they show up for some reason.
2)Killfeed, chat and pop-up notifications (e.g. Strange Weapons Level-Up or Trade Requests) do not show up, nor do they play any sound.
3)The killcam screen leaves black borders on the bottom and right sides of the screen, as shown in the picture below.
![img1](https://user-images.githubusercontent.com/40694857/42101609-d777efe2-7bc3-11e8-9afc-37ca6263c373.png)
4)This only happened once, but player models _might_ look like they're t-posing while still being able to shoot.
5) Shader quality is set to High in the options for some reason.
6)This is really a small thing, but there's this small black bar on my menu and I don't know what might be causing it. Picture related.
![img2](https://user-images.githubusercontent.com/40694857/42101610-d7a1ed56-7bc3-11e8-9882-3a6ffc414ab4.png)

    * How you encountered the issue
       As soon as I started the game, after putting the preset and the addons in the custom folder.
    * Config version (don't say latest, say the actual version, found in the
      startup console output)

    * Config preset and addon(s)
      Very Low Preset, No Soundscapes, No Extra Models, No Pyroland, No Tutorial addons.
      I used to play on Low Preset (can't remember the version sadly) with the aforementioned addons 
      plus the No Footstep Addon and none 
      of these problems showed up.
    * Custom values (if any)
      What are those?
    * DX level
       81
    * Launch options
      -novid -nojoy -nosteamcontroller -noff -softparticlesdefaultoff -reuse 
    * Operating system (OS)
      Windows 10 
    * Graphics card (GPU)
      NVIDIA GeForce GT 610
    * Processor (CPU)
      Intel Core i5 4 CPUs ~3,2 GHz
    * HDD or SSD
       HDD 
    * RAM size in MB or GB
      6144 MB

**Comment by mastercoms** [comment] 2018-06-30 05:56
1) Not sure why this one happens. I'm looking into it. Duplicate of #57.
2) This is a feature of the very low preset.
You can change the HUD modules:
https://github.com/mastercoms/mastercomfig/wiki/Modules#hud-modules

As for notifications:
```c
cl_notifications_show_ingame 1
cl_notifications_max_num_visible 1
```
3) This is a TF2 bug when running at a lower 3D resolution. Set `mat_viewportscale 1`.
4) Not sure about this one. Probably a TF2 bug.
5) This is intentionally set for performance reasons, as low shader quality uses a lower DirectX feature level which may result in lower performance on most modern graphics cards. The badgpu addon turns it to low.
6) TF2 bug. It's the party chat.

**Closed as completed** 2018-06-30 05:57 UTC
Labels: Priority: minor, Type: bug, Category: graphical misc

**Comment by jonnemenes** [comment] 2018-06-30 17:28
well thanks a lot sir, should I put these commands in my custom.cfg or type them in console?

**Comment by mastercoms** [comment] 2018-06-30 17:35
Custom.cfg.

**Comment by jonnemenes** [comment] 2018-06-30 18:39
ok, thanks for all the help, godspeed you!!
