### ISSUE TITLE
Bug: (Artifacts?) when looking around 

### ISSUE THREAD

**Issue by gmod64bit** [mastercoms/tf2cfg#418] opened 2020-11-17 20:44 UTC
**Describe the bug**
When looking around, screen flashes black, same as this guys #407 

**How you encountered the issue**
Installing mastercomfig, playing any lobby 

**Screenshots**
#407 had used this video which is identical to my own problem 
https://www.youtube.com/watch?v=edyLdumbWwE

**Desktop (please complete the following information):** xmonad [window manager]
* Config version: mastercomfig version : 9.1.0 | November 1, 2020 
* Config preset and addon(s): low -- no pryovision / no tutorials / null canceling movement 
* Custom values (if any):
* DX level: opengl
* Launch options:
* Operating system (OS): GNU/Linux
* Graphics card (GPU):  Radeon RX Vega 64
* Graphics driver version: amdgpu 
* Processor (CPU): Ryzen 3600x
* TF2 on HDD or SSD: SSD
* Memory (RAM) size in MB or GB: 16GB

__________________________

I have tested this on a fresh install and have concluded this only occurs after I install mastercomfig. What could this be?

**Comment by melvyn2** [comment] 2020-11-17 20:45
did you try any of the fixes mentioned in #407 ?

**Comment by cloutlord420** [comment] 2020-11-17 20:46
This is not bug in mastercomfig but rather it is bug in mesa 20.2.x. The mat_phong 0 setting in mastercomfig may exasperate this issue but it is not root cause.

**Comment by gmod64bit** [comment] 2020-11-17 20:46
> did you try any of the fixes mentioned in #407 ?

I actually did try what was suggested - downgrading mesa and mat_phong 0. I also tried mesa-git but unfortunately no avail.

**Comment by melvyn2** [comment] 2020-11-17 20:47
There is no fix in mesa yet, so mesa-git would make no difference. What version did you downgrade to?

**Comment by gmod64bit** [comment] 2020-11-17 20:50
> This is not bug in mastercomfig but rather it is bug in mesa 20.2.x. The mat_phong 0 setting in mastercomfig may exasperate this issue but it is not root cause.

Yeah that's what I read in #407 however, this only happens when applying mastercomfig, any clues to what it may be that triggers this? It never happens when playing vanilla



> There is no fix in mesa yet, so mesa-git would make no difference. What version did you downgrade to?

I tried  20.0.0 | 19.2.0 | 19.0.0

**Comment by gmod64bit** [comment] 2020-11-17 21:01
Oooooooh, mesa 19.3.0-1 fixed it for me!

**Comment by Tiagoquix** [comment] 2020-11-20 22:10
@mastercoms This issue can be closed for the time being.

**Comment by gmod64bit** [comment] 2020-11-22 17:54
> @mastercoms This issue can be closed for the time being.

Oh, so that fix worked for about five games. Doesn't seem to matter the mesa version anymore.

**Comment by melvyn2** [comment] 2020-11-22 17:55
https://github.com/ValveSoftware/Source-1-Games/issues/3443

**Comment by gmod64bit** [comment] 2020-11-23 16:21
> [ValveSoftware/Source-1-Games#3443](https://github.com/ValveSoftware/Source-1-Games/issues/3443)

Just read the same fix here

https://gitlab.freedesktop.org/mesa/mesa/-/issues/3514#note_702564

This is lovely, I am going to test it! 

_____________
** WORKED**

**Comment by RicochetYT** [comment] 2020-11-23 16:25
What made the artifacts disapear (for the most part for me) is to add mat_bumpmap 1 to your gameoverides.cfg or whatever.

**Comment by gmod64bit** [comment] 2020-11-23 16:26
> What made the artifacts disapear (for the most part for me) is to add mat_bumpmap 1 to your gameoverides.cfg or whatever.

Making mat_bumpmap 0 was my cure! Hooray, I can play TF2 again =]

**Comment by mastercoms** [comment] 2021-01-22 20:40
Fixed in b6258a9. (added to troubleshooting docs)

**Closed as completed by mastercoms** 2021-01-22 20:40 UTC
Labels: Type: bug
