### ISSUE TITLE
what happened with the openGL optimizations?

### ISSUE THREAD

**Issue by ghost** [mastercoms/tf2cfg#753] opened 2024-06-17 16:12 UTC
what happened with the OpenGL optimizations on the mastercomfig page? this could probably let a lot of players that have no vulkan support on their GPUs to use an outdated mastercomfig version, i've also seen that TF2 vulkan occasionally lags a lot, we need the old GL optimizations back

**Comment by mastercoms** [comment] 2024-06-19 19:24
dupe of #752

**Closed as completed by mastercoms** 2024-06-19 19:24 UTC
Labels: Type: bug
